Create team-contract.md
UBC-MDS/MDS_Winery_Dashboard pull request #7
Opened 2021-01-12 00:56 UTC by mgaroub

Team contract created. Please review and accept.

2021-01-12 15:00 UTC, kmoravej requested changes
Thanks @mgaroub. I do not think we need to include interests, weaknesses, and strength in the contract. The main goal is to write a contract. We need to reformat it as well and make some tales and  headings.

2021-01-12 16:06 UTC, mgaroub commented
Thanks @kmoravej. The formatting is fine. I will remove the interests, weaknesses and strengths as suggested.

2021-01-12 16:21 UTC, nphaterp approved these changes
LGTM

2021-01-13 03:51 UTC, kmoravej approved these changes

2021-01-13 03:52 UTC, merged